version: "3"

services:
  redis:
    image: redis:alpine
    
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
